### ISSUE TITLE
Make loltext message style configurable

### ISSUE THREAD

**Issue by greggles** [mroth/lolcommits#148]
I've figured out that if I disable the loltext plugin then the commit hash and commit message will be removed from the image. It would be nice to be able to configure:

* font size for hash and the message, separately from each other
* whether hash or commit appears, and in what corner

**Comment by dbeckham** [comment]
Don't forget text alignment, especially centered.

**Comment by mylescc** [comment]
Has there been any progress on this? A guy on my dev team is desperate to change the font size...

**Comment by matthutchinson** [comment]
I've actually [been working](https://github.com/mroth/lolcommits/compare/configurable-loltext) on this a little this week, should have a PR merged this weekend and a new gem release shortly after that.

**Comment by mylescc** [comment]
Awesome, thanks @matthutchinson .

**Comment by matthutchinson** [comment]
PR #282 opened, if/when it gets merged i'll close this issue :+1:
