### ISSUE TITLE
refactor out Choice gem in favor of Methadone

### ISSUE THREAD

**Issue by mroth** [mroth/lolcommits#259]
Since we already depend on Methadone for our CLI tests and logging, and it can handle CLI parsing as well, we should eventually migrate Choice out to remove another gem dependency.

This will be much easier once we handle the Configuration structural refactors, and certainly will remove less gems than #99, so its probably a "nice to have" for later on.

**Comment by matthutchinson** [comment]
FYI, i've started looking into this.. pr available shortly 😄
