### ISSUE TITLE
Invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by hagerhink** [mroth/lolcommits#268]
When using lolcommits, one of my commit messages contained an "Ö", which produced an "invalid byte sequence in US-ASCII (ArgumentError)". All subsequent commits now produce this error and fails to capture an image, regardless of commit message. Have tried to disable and reenable lolcommits aswell as reinstalling it without any luck. 

Stack trace:
```
/Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:846:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:846:in `command_lines'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:145:in `full_log_commits'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:119:in `run_log'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:112:in `check_log'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/git-1.2.9.1/lib/git/log.rb:89:in `first'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/lib/lolcommits/git_info.rb:14:in `initialize'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/lib/lolcommits/runner.rb:18:in `new'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/lib/lolcommits/runner.rb:18:in `initialize'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/bin/lolcommits:134:in `new'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/bin/lolcommits:134:in `block in do_capture'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/bin/lolcommits:148:in `fork_me?'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/bin/lolcommits:118:in `do_capture'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/lolcommits-0.5.7/bin/lolcommits:384:in `<top (required)>'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/bin/lolcommits:23:in `load'
	from /Users/henrikhansson/.rvm/rubies/ruby-2.1.2/bin/lolcommits:23:in `<main>'
	from /Users/henrikhansson/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/henrikhansson/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>' 
```

**Comment by matthutchinson** [comment]
Looks like the git gem is having trouble reading your commit message from an earlier commit due to encoding issues.  I've been unable to replicate the bug here probably because I can't get the exact char sequence you have in that message.  I've tried a commit with that char, and other weird chars including emoji's and they all still work.

To help debug can you provide the output of `locale` on your machine, and can you create a new empty git repo, use the exact same commit message you believe is causing the issue, and try lolcommits there?

**Comment by matthutchinson** [comment]
Digging further, it seems there are [a few issues](https://github.com/schacon/ruby-git/issues?q=is%3Aopen+encoding+is%3Aissue) with the git gem we are using around encoding (and one [un-merged PR](https://github.com/schacon/ruby-git/pull/190) that suggests a fix).  I'll add a comment on one of the existing issues that we're having the same problem.

**Comment by matthutchinson** [comment]
One other thing, can you try the following;

    echo $LANG

(and paste the output, then create a new ruby file with this content and run it)

    echo "p __ENCODING__ " >> test.rb
    ruby test.rb  

(and paste the output)

**Comment by hagerhink** [comment]
Unfortunately, I am no longer able to reproduce the error in the old repo or a new one.

Using lolcommits (0.5.7)

locale:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

echo $LANG:
```
(no output, just a blank row)
```

ruby test.rb
```
#<Encoding:UTF-8>
```

**Comment by matthutchinson** [comment]
Werid, OK can we close this for now? Given the bug is originating from the git gem.  We'll be sure to keep up with any fixes they release and push out a new version of lolcommits.

**Comment by hagerhink** [comment]
Haha, yeah, it's totally fine by me :)
