### ISSUE TITLE
Remove hardcoded commit message and SHA-1 from image

### ISSUE THREAD

**Issue by LandonSchropp** [mroth/lolcommits#273]
Thanks for creating this! We've had a lot of fun with it around the office.

Is there any way to remove the commit message and SHA-1 from the image? I didn't see anything in the readme.

**Comment by jastkand** [comment]
There is mention about this on [wiki page](https://github.com/mroth/lolcommits/wiki/Configuring-Plugins). You just need to turn off the `loltext` plugin.

**Comment by matthutchinson** [comment]
Yep, type ,

`lolcommits --config -p loltext`

and when prompted, set enabled as false
