### ISSUE TITLE
Could not create capture session after upgrading to Mac OS X El Capitan

### ISSUE THREAD

**Issue by indieveed** [mroth/lolcommits#287]
After upgrading Mac OS X to the latest version (El Capitan), capturing stopped working.

```
 % lolcommits -c
*** Preserving this moment in history.
	Could not create capture session.
Error.
```

**Comment by robertdodd** [comment]
Yeah, me too. I get:

    .git/hooks/post-commit: line 5: lolcommits: command not found

**Comment by robertdodd** [comment]
I fixed it by installing again:

     (sudo) gem install lolcommits

**Comment by indieveed** [comment]
I've tried to reinstall previously without any success, but now it helped. May be was fixed in latest release.
