### ISSUE TITLE
Windows 10: debug shows that all plugins are disabled

### ISSUE THREAD

**Issue by robiningelbrecht** [mroth/lolcommits#305]
I have enabled the slack, uplolzd and tranzlate plugins. These are all in my config.yml located in the folder where all the images are saved. All seems to look good, but nothing happens. When I enable debug mode in my post-commit hook, it tells me all above plugins are disabled. The only one that is enabled is loltext.... Could this be a bug or am I doing something wrong?

**Comment by matthutchinson** [comment]
Can you paste your config.yml here so I can look into it?  Also, how did you configure the plugins? Via the regular `lolcommits --config`?

**Comment by robiningelbrecht** [comment]
Yes, I installed them via the _lolcommits --config_ command. This is my config.yml (slack is already disabled again. Maybe important to mention. The settings for loltext are ignored as well. So it is as if the config.yml file isn't there:

```
---
loltext:
  enabled: true
  :message:
    :color: 
    :font: 
    :position: 
    :size: 30
    :stroke_color: 
  :sha:
    :color: 
    :font: 
    :position: 
    :size: 20
    :stroke_color: 
tranzlate:
  enabled: true
uploldz:
  enabled: true
  endpoint: http://www.my-website.be/lolcommits
  optional_key: my_key
  optional_http_auth_username: 
  optional_http_auth_password: 	
```

**Comment by robiningelbrecht** [comment]
the the .plugins directory in .lolcommits is empty as well.. don't know if this is a normal thing?

**Comment by matthutchinson** [comment]
Ok, nothing looks to bad there, I'm going to get a Windows 10 VM set up to debug further.  Will report back here.

(you can ignore .plugins, its currently not in use).

**Comment by robiningelbrecht** [comment]
FIY, this is the debug log: 
`D, [2016-05-19T07:13:58.326305 #9348] DEBUG -- : Outputting at DEBUG verbosity
D, [2016-05-19T07:13:58.348822 #9348] DEBUG -- : Walking up dir tree
D, [2016-05-19T07:13:58.349822 #9348] DEBUG -- : GitInfo: parsed the following values from commit:
D, [2016-05-19T07:13:58.369839 #9348] DEBUG -- : GitInfo: 	Formatted code
D, [2016-05-19T07:13:58.370339 #9348] DEBUG -- : GitInfo: 	04c626f3001
D, [2016-05-19T07:13:58.370339 #9348] DEBUG -- : GitInfo: 	C:/wamp/www/_GIT/my_project/.git
D, [2016-05-19T07:13:58.415841 #9348] DEBUG -- : GitInfo: 	user/project
D, [2016-05-19T07:13:58.433858 #9348] DEBUG -- : GitInfo: 	master
D, [2016-05-19T07:13:58.433858 #9348] DEBUG -- : GitInfo: 	user.name
D, [2016-05-19T07:13:58.433858 #9348] DEBUG -- : GitInfo: 	user.name@domain.com
D, [2016-05-19T07:13:58.440375 #9348] DEBUG -- : Runner: precapture about to execute Lolcommits::Tranzlate
D, [2016-05-19T07:13:58.440375 #9348] DEBUG -- : Plugin: Lolcommits::Tranzlate: Initializing
D, [2016-05-19T07:13:58.440876 #9348] DEBUG -- : Plugin: Lolcommits::Tranzlate: Disabled, doing nothing for precapture execution
*** Preserving this moment in history.
D, [2016-05-19T07:13:58.440876 #9348] DEBUG -- : Capturer: initializing new instance #<Lolcommits::CaptureWindows:0x00000005a41c08>
D, [2016-05-19T07:14:02.665078 #9348] DEBUG -- : Runner: resizing snapshot
D, [2016-05-19T07:14:02.850931 #9348] DEBUG -- : Runner: copying resized image to C:\Users\robin-entityone/.lolcommits/caractere/04c626f3001.jpg
D, [2016-05-19T07:14:02.854881 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: Initializing
D, [2016-05-19T07:14:02.854881 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: I am enabled, about to run postcapture
D, [2016-05-19T07:14:02.855412 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: Annotating image via MiniMagick
D, [2016-05-19T07:14:02.990700 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: annotating message text to image
D, [2016-05-19T07:14:02.991200 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: annotating sha text to image
D, [2016-05-19T07:14:02.991340 #9348] DEBUG -- : Plugin: Lolcommits::Loltext: Writing changed file to C:\Users\robin-entityone/.lolcommits/caractere/04c626f3001.jpg
D, [2016-05-19T07:14:03.119265 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::DotCom
D, [2016-05-19T07:14:03.119265 #9348] DEBUG -- : Plugin: Lolcommits::DotCom: Initializing
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::DotCom: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::Lolsrv
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::Lolsrv: Initializing
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::Lolsrv: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::LolTumblr
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolTumblr: Initializing
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolTumblr: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::LolSlack
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolSlack: Initializing
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolSlack: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::LolProtonet
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolProtonet: Initializing
D, [2016-05-19T07:14:03.120685 #9348] DEBUG -- : Plugin: Lolcommits::LolProtonet: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::LolYammer
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::LolYammer: Initializing
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::LolYammer: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::LolTwitter
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::LolTwitter: Initializing
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::LolTwitter: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Runner: postcapture about to execute Lolcommits::Uploldz
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::Uploldz: Initializing
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Plugin: Lolcommits::Uploldz: Disabled, doing nothing for postcapture execution
D, [2016-05-19T07:14:03.121201 #9348] DEBUG -- : Runner: running cleanup
`

**Comment by matthutchinson** [comment]
Really weird, I've setup Windows 10 (64bit) Ruby 2.3.0 and ImageMagick 7 in my VM and using your config file, it all works fine..

![screen shot 2016-05-20 at 16 33 37](https://cloud.githubusercontent.com/assets/2095/15433086/bd29fc68-1ea8-11e6-9f64-72888ada5609.png)

All the plugins that should be enabled are, and the capture works.  I assume you've tried deleting the config file, and reconfiguring each plugin one by one with;

    lolcommits --config

Failing that, can you tell me exactly what version of Ruby are you on, and the output of `gem list`?  Though I have a feeling this is something to do with your Windows filesystem being unable to read the config file.. like you said your output looks like the config file isn't there.  Can you check if there are any weird permission settings with this file or the folder tree?

**Comment by robiningelbrecht** [comment]
Tried to re-configure, without any result... In regards with the permissions. If the system was unable to read the file, how could it write it in the first place?

My ruby version is 
![image](https://cloud.githubusercontent.com/assets/203894/15461170/cc387b0a-20b8-11e6-8e49-8442a70c32cc.png)

And the list outputted by _gem list_ is
![image](https://cloud.githubusercontent.com/assets/203894/15461229/7e91d3c8-20b9-11e6-926e-401406ffc958.png)
![image](https://cloud.githubusercontent.com/assets/203894/15461235/8622d0a6-20b9-11e6-9c6f-d6ac7939200e.png)

**Comment by robiningelbrecht** [comment]
FYI: I updated ruby to 2.3. Still no reults...

**Comment by robiningelbrecht** [comment]
UPDATE: I found "the bug" by looking at your screenshot. config.yml is placed in the root lolcommit directory by default. When I copy this file to the lolcommit/my_repo directory, it all works fine...

**Comment by robiningelbrecht** [comment]
So if I'm correct, the config.yml has to be located in a subdirectory of the lolcommits folder? Is it possible to add a general config.yml for all your prokects?

**Comment by matthutchinson** [comment]
So the config file, needs to be in this folder;

    # e.g. if your Windows username was matt and your repo name was 'my_project'
    C:/Users/matt/.lolcommits/my_project/config.yml

It is possible to set an `LOLCOMMITS_DIR` [environment variable](https://github.com/mroth/lolcommits/wiki/Configure-Commit-Capturing#environment-variables) to change this, but i'm not sure how that is done in Windows (with `SET LOLCOMMITS_DIR={full path to folder}`)

Couple more questions..

Where exactly is your config file, and where exactly is the repository located (the full path)?
In the repository your attempting to get this to work, what does running this return?

    lolcommits --show-config

When you configure the plugin, do you get a message like this after configuring;

    Successfully configured plugin: loltext at path 'C:/Users/matt/.lolcommits/my_project/config.yml'

Do you have any weirdly named directories on your path to the repo? E.g. with spaces or weird characters?

**Comment by robiningelbrecht** [comment]
Matt,

The problem was that I enabled a plugin outside of my git repo. That's why the config.yml wasn't placed in the correct directory (I think). So after all, everything seems to work fine, I fucked up on my side, sorry :(

Extra question: Is it possible to use one config file for all my projects? So when no config.yml is found in _.lolcommits/my_repo_, the one in _.lolcommits/_ is used?

**Comment by matthutchinson** [comment]
Ah-ha! we need to put in a better warning or error message for that (enabling a plugin from a non git repo dir).  I'll create another issue to track adding that feature.

For your extra question, unfortunately its currently not possible to have a single lolcommits config for all projects, the only way to do it right now would be to symlink the config file across your ~/.lolcommits/{repos_name} directories.  Again, its probably a feature worth having, so will add an issue to track that too (if we don't already have one) :).
