### ISSUE TITLE
Update mini_magick

### ISSUE THREAD

**Issue by Ruxton** [mroth/lolcommits#311]
MiniMagick is currently held due to some old JRuby issues which look to be fixed.

What are the chances of bumping this up and maybe finally being able to get rid of the excess quoting currently happening :(

![c5d5c73cf72](https://cloud.githubusercontent.com/assets/382760/16294194/e081745c-3951-11e6-94e1-8c706bebfbba.jpg)

I built my last PR against a newer version of minimagick to stop the above occurring.

**Comment by matthutchinson** [comment]
to clarify, by the above, I assume you mean the quotes appearing on both the sha and msg txt?  
If a newer version of mini_magick works OK, it should be fine to upgrade the gemspec.  The only other [condition is for 1.8](https://github.com/mroth/lolcommits/issues/310) ...

**Comment by matthutchinson** [comment]
Discussion on this moved to #310
