### ISSUE TITLE
Incorrect hook error

### ISSUE THREAD

**Issue by a-x-** [mroth/lolcommits#316]
i have `.git/hooks/post-commit` hook file contents:
`#!/usr/bin/env sh`

shebang in my hook is correct and relates to shell best practices.

i have error with `lolcommits`:
> the existing hook (at .git/hooks/post-commit) doesn't start with a good shebang; like #!/bin/sh

**Comment by matthutchinson** [comment]
ah, sorry about that, i'll issue a fix soon, to update the regex this checks against.

Basically [here](https://github.com/mroth/lolcommits/blob/master/lib/lolcommits/backends/installation_git.rb#L102)

**Comment by matthutchinson** [comment]
The above PR (now merged) fixes this issue, I'll release a new version of the gem soon.
