### ISSUE TITLE
Build failing on Ruby 2.4

### ISSUE THREAD

**Issue by mbi** [mroth/lolcommits#327]
Installation is currently failing on Ruby 2.4 because json-1.8.3 fails to build ([full gist](https://gist.github.com/mbi/43aaf52fd636cbf0984953d2b0342f71)). 

- Relevant upstream issue: https://github.com/flori/json/issues/303
- Same (?) issue in Rails: https://github.com/rails/rails/issues/27450

**Comment by matthutchinson** [comment]
Im working on a fix right now, should be ready tonight, there are several issues with 2.4

**Comment by mbi** [comment]
Thank you!
