### ISSUE TITLE
MiniMagick::Error - mogrify: non-conforming drawing primitive definition `path'

### ISSUE THREAD

**Issue by mrchimp** [mroth/lolcommits#371]
I'm getting the following error on OSX 10.13.4. Ruby v2.3.3p222

```
/Library/Ruby/Gems/2.3.0/gems/mini_magick-4.8.0/lib/mini_magick/shell.rb:17:in `run': `mogrify -strokewidth 2 -interline-spacing -9 -stroke black -fill white -gravity SouthWest -pointsize 48 -font /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf -annotate +10+10 Constrain Enso version /var/folders/27/j1wxv8d56vl986ch5mwv_ffh0000gn/T/mini_magick20180509-9559-5neg83.jpg` failed with error: (MiniMagick::Error)
mogrify: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/4126.
        from /Library/Ruby/Gems/2.3.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:92:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:40:in `new'
        from /Library/Ruby/Gems/2.3.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:564:in `mogrify'
        from /Library/Ruby/Gems/2.3.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:444:in `combine_options'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/loltext.rb:118:in `annotate'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/loltext.rb:88:in `run_post_capture'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:31:in `block in execute_plugins_for'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:29:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:29:in `execute_plugins_for'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:54:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/bin/lolcommits:157:in `block in capture_lolcommit'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:23:in `block in fork_me?'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:22:in `fork'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:22:in `fork_me?'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/bin/lolcommits:150:in `capture_lolcommit'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/bin/lolcommits:70:in `block in <class:App>'
        from /Library/Ruby/Gems/2.3.0/gems/methadone-1.9.5/lib/methadone/main.rb:395:in `call_main'
        from /Library/Ruby/Gems/2.3.0/gems/methadone-1.9.5/lib/methadone/main.rb:167:in `go!'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/bin/lolcommits:203:in `<class:App>'
        from /Library/Ruby/Gems/2.3.0/gems/lolcommits-0.12.1/bin/lolcommits:17:in `<top (required)>'
        from /usr/local/bin/lolcommits:22:in `load'
        from /usr/local/bin/lolcommits:22:in `<main>'
```

**Comment by matthutchinson** [comment]
What version of ImageMagick do you have installed? e.g. run `convert --version`

**Comment by mrchimp** [comment]
`7.0.7-31`

**Comment by streeetlamp** [comment]
Similar, OSX 10.13.4
ruby 2.5.1p57
ImageMagick 7.0.7-31
lolcommits v0.12.1

`22: from /usr/local/bin/lolcommits:23:in `<main>'
        21: from /usr/local/bin/lolcommits:23:in `load'
        20: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/bin/lolcommits:17:in `<top (required)>'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/bin/lolcommits:203:in `<class:App>'
        18: from /usr/local/lib/ruby/gems/2.5.0/gems/methadone-1.9.5/lib/methadone/main.rb:167:in `go!'
        17: from /usr/local/lib/ruby/gems/2.5.0/gems/methadone-1.9.5/lib/methadone/main.rb:395:in `call_main'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/bin/lolcommits:70:in `block in <class:App>'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/bin/lolcommits:150:in `capture_lolcommit'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:22:in `fork_me?'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:22:in `fork'
        12: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/cli/process_runner.rb:23:in `block in fork_me?'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/bin/lolcommits:157:in `block in capture_lolcommit'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:54:in `run'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:29:in `execute_plugins_for'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:29:in `each'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-0.12.1/lib/lolcommits/runner.rb:31:in `block in execute_plugins_for'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/loltext.rb:88:in `run_post_capture'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/loltext.rb:118:in `annotate'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:444:in `combine_options'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:564:in `mogrify'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:40:in `new'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:92:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/shell.rb:17:in `run': `mogrify -strokewidth 1 -interline-spacing -9 -stroke black -fill white -gravity SouthWest -pointsize 24 -font /usr/local/lib/ruby/gems/2.5.0/gems/lolcommits-loltext-0.0.7/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf -annotate +10+10 some ascii art for the kids /var/folders/pz/9y_d6l1501jcplj5qly9p5sh0000gp/T/mini_magick20180509-24026-6fjuyz.gif` failed with error: (MiniMagick::Error)
mogrify: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/4126.`

**Comment by mbi** [comment]
Same on OSX 10.11.6, lolcommits v0.12.1 with ImageMagick 7.0.7-31, ruby 2.5.1p57, both from Homebrew.

**Comment by matthutchinson** [comment]
Looks like the ImageMagick `mogrify` command will no longer accept the args we use to annotate text in ImageMagick 7.. 

If you need this working urgently you could `brew install imagemagick@6` for now. I'll look at implementing and releasing a fix asap.

**Comment by matthutchinson** [comment]
I believe [this](https://github.com/lolcommits/lolcommits-loltext/pull/4) will fix the issue for now, will release a new `lolcommits-loltext` gem version soon.

**Comment by matthutchinson** [comment]
OK, just released lolcommits-loltext `v0.0.8` can you all try this to update?

    gem uninstall lolcommits-loltext
    gem install lolcommits-loltext

**Comment by matthutchinson** [comment]
Yes please. I'll close if everyone's good 👍

**Comment by mbi** [comment]
Also good, thank you! 👍
