### ISSUE TITLE
Require plugin gems from lolcommits

### ISSUE THREAD

**Issue by alu0100816167** [mroth/lolcommits#374]
Hello, I just wanted to know how lolcommits requires external plugins plugins. 
I mean, how it includes them so they can be used within lolcommits. I've read the 'Developing your own plugin' guide, but, i dont understand yet how lolcommits adds code from a `gem install lolcommits-pluginX`. 

If someone could point me where exactly this process is done I would be very thankfull. 👍

**Comment by matthutchinson** [comment]
See the [PluginManager](https://github.com/mroth/lolcommits/blob/master/lib/lolcommits/plugin_manager.rb) class, thats where the magic happens for loading and requiring plugin gems.  The code should be pretty self explanatory.    Each found plugin (based on the gem's name, becomes an instance of a [GemPlugin](https://github.com/mroth/lolcommits/blob/master/lib/lolcommits/gem_plugin.rb), which is then used in the `Lolcommits::Runner` (and config) classes.
