### ISSUE TITLE
Works but never exits

### ISSUE THREAD

**Issue by mrchimp** [mroth/lolcommits#381]
Every time I commit, lolcommits does its thing and the image is generated correctly but I see `*** Preserving this moment in history.` and I'm not returned to the prompt until I press enter.

It's not a big deal but it is a small annoyance every time I commit.

**Comment by matthutchinson** [comment]
Weird, can I ask what version of the gem you're using and what platform?

**Comment by mrchimp** [comment]
OS X 10.13.6 (though this was happening on earlier version too)
lolcommits-0.12.1.gem

**Comment by mrchimp** [comment]
Is there a log? Maybe there is something that isn't actually working right, even though the image is created?

**Comment by matthutchinson** [comment]
So for me it works fine..  Can I ask what version of Ruby your'e using;

    ruby -v

And what lolcommit plugins you have installed (if any)

    lolcommits --plugins

Also, the content of your git capture hook

    cat {your-repo}.git/hooks/post-commit

Running a capture from the command line with `--debug` might offer more info

    # from within your repo directory
    lolcommits -c --debug

**Comment by matthutchinson** [comment]
I know its a pain but you could try uninstalling and reinstalling gem(s):

    # in your repo
    lolcommits --disable 
    gem uninstall lolcommits
    gem uninstall lolcommits-loltext
    gem uninstall lolcommits-{any-other-plugins}

**Comment by mrchimp** [comment]
I'm not sure if this is related but I've noticed some text overflows the image. It sometimes wraps to two lines, but I can see some where it has overflowed on a single line and some where it has overflowed on the second line.

**Comment by matthutchinson** [comment]
Ok, what version of ImageMagick are you running?  I'm on `imagemagick: stable 7.0.8-12 (bottled), HEAD` from `brew install imagemagick`.

Also does mogrify work for you out of the box on other images?  E.g. try something like this from the command link on `any-image.jpg`:

`mogrify -strokewidth 2 -interline-spacing -9 -stroke black -fill white -gravity SouthWest -pointsize 48 -font /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.9/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf -annotate +10+10 test 2 any-image.jpg`

if that fails, check if the font file at ` /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.9/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf` exists OK.

**Comment by tnorthcutt** [comment]
I'm having the same problem. Just disabled, uninstalled, and reinstalled; no change.

Versions:
lolcommits: `v0.12.1`
imagemagick: `stable 7.0.8-12 (bottled)`
ruby: `2.4.2p198`

No lolcommits plugins (aside from loltext).

Running
```
mogrify -strokewidth 2 -interline-spacing -9 -stroke black -fill white -gravity SouthWest -pointsize 48 -font /Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.9/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf -annotate +10+10 test 2 any-image.jpg
```
on an image results in `test` being added to the image, but also the following cli output:

```
mogrify: unable to open image '2': No such file or directory @ error/blob.c/OpenBlob/3489.
mogrify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.
mogrify: unable to read font `/Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.9/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf' @ warning/annotate.c/RenderType/1009.
mogrify: unable to read font `/Library/Ruby/Gems/2.3.0/gems/lolcommits-loltext-0.0.9/lib/lolcommits/plugin/../../../vendor/fonts/Impact.ttf' @ warning/annotate.c/RenderType/1009.
```

**Comment by matthutchinson** [comment]
I think this might be an issue with the plugin gem `lolcommits-loltext`, what does command return for you?

    gem list | grep lolcommits-loltext

I'd like to know the version you have installed.

**Comment by tnorthcutt** [comment]
Correct @matthutchinson, `v0.0.9`.

**Comment by matthutchinson** [comment]
Can you tell me the version of `mini_magick` you have installed? Still having trouble replicating this with exact same version #'s you have. I feel its down to how the `annotate` (in this case `test 2`) argument to mogrify isn't being quoted correctly.  

Do single word commits work OK for you? (i.e. no spaces)

**Comment by matthutchinson** [comment]
Hi again, @tnorthcutt can you try running with the `--debug` flag and paste the output?

**Comment by matthutchinson** [comment]
Sorry - I think I was chasing a red herring with the quotes around the commit message thing. I believe that it's correctly quoted.

But the `mogrify: non-conforming drawing primitive definition path` error (see @mrchimp's debug output) is a problem in ImageMagick and seems to have cropped up a few times in the [past](http://studio.imagemagick.org/discourse-server/viewtopic.php?t=34017&p=156261).

In @mrchimp's case it seems the command to annotate the sha worked, but not the commit message.
I'm not sure how to take this further without being able to repeat it.

Some other things to send me or try:

* `lolcommits --show-config`
* `gem list | grep mini_magick`
* Try a different (maybe older) version of ImageMagic e.g. with `brew install imagemagick@6; brew link imagemagick@6`

I've been planning to replace using ImageMagick in lolcommits for a long time, maybe its time to finally get started on that.

**Comment by matthutchinson** [comment]
Had another go trying this on High Seirra (10.13.6) with ImageMagick (7.0.7-31); still worked fine for me.

Also, if you're reinstalling ImageMagick, make sure it is completely removed and unlinked before installing again.

    brew unlink imagemagick
    brew uninstall imagemagick
    # and check it is gone with
    convert --version

    # then install the latest (now 
    brew install imagemagick

Will close this shortly, since I can't repeat and I have no more info to go on..
