### ISSUE TITLE
lolcommits fails to capture image on linux

### ISSUE THREAD

**Issue by rogeruiz** [mroth/lolcommits#387]
This issue seems slightly related, but different enough for its own, to #370. I'm having issues capturing anything on my Linux setup. I'm using Pop!_OS 18.10 with Gnome 3.30.2

I've followed all the instructions on how to install on linux, but anytime I try to capture something, I get the following error 
```
Lolcommits::Runner: running all enabled plugin hooks for pre_capture
*** Preserving this moment in history.
Capturer: initializing new instance #<Lolcommits::CaptureLinux:0x000056419bf0c6b0>
LinuxCapturer: making tmp directory
LinuxCapturer: calling out to mplayer to capture image
LinuxCapturer: calling out to mplayer to capture image
LinuxCapturer: failed to capture any image
Runner: failed to capture a snapshot
``` 

I dug into the code, and found the calls to `mplayer` here:
https://github.com/mroth/lolcommits/blob/129f37691b86492b5a307f4d878348363479819f/lib/lolcommits/capturer/capture_linux.rb#L23

When I ran that command myself to see what it would capture, or what error it was outputting I found that `mplayer` would fail to capture anything if I passed the `~/` path instead of an absolute path. It only worked with the second command. (The commands below use variables to redact the actual text there. I ran them without string interpolation)

Doesn't work
```
mplayer -vo jpeg:outdir=~/.lolcommits/${repo_name}/  -frames 25 -fps 25 tv://
```

Works and captures images.
```
mplayer -vo jpeg:outdir=/home/${username}/.lolcommits/${repo_name}/  -frames 25 -fps 25 tv://
```

Is it possible that `Dir.mktmpdir` isn't passing an absolute directory path to `mplayer` and causing the failure? I can attempt to submit a patch if that's the case. Thanks!

**Comment by rogeruiz** [comment]
Actually I think I found the issue, the `#{capture_device_string}` seems to be incorrect for my system. I haven't set one, so it's defaulting to `-tv device="/dev/video1"` which causes `mplayer` to fail with: 

```
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.
```

**Comment by rogeruiz** [comment]
Okay, so I think I solved this for myself by passing the `LOLCOMMITS_DEVICE` variable pointing to the right device. I think updating documentation would be helpful for folks to debug this. I'll submit a PR this weekend. But for now I'll close this issue out as it's working for me.

**Comment by rogeruiz** [comment]
for anyone who finds this issue, I iterated on using `LOLCOMMITS_DEVICE` set to the appropriate `/dev/video${INDEX}` until it worked. Thankfully I only had two and the first one worked. :+1:

**Comment by rogeruiz** [comment]
Researching this more, it looks like the issue i encountered was introduced in this commit. https://github.com/lolcommits/lolcommits/commit/c639c066e76948c86a3948eb9a25989a38885217

**Comment by tbruckmaier** [comment]
@rogeruiz Thanks for your investigation and the workaround with `LOLCOMMITS_DEVICE`, works for me. Could you reopen this issue so maybe there will be a proper fix once?

**Comment by matthutchinson** [comment]
What should a "proper fix" look like here, I guess on Linux I could always choose to prompt the user and ask which device they want to set? (if there are multiple `/dev/video[0-9]+` found when running lolcommits install).

We've had few issues with this over the years, so I'm tempted to keep it as is.  The [README](https://github.com/lolcommits/lolcommits#capture-configuration-options) does mention how to set a different device with the ENV var or `--device` flag.

**Comment by rvangsgaard** [comment]
Asking the user could confuse the user - how do a user test which video device works?

But I would still prefer to be asked (with the first being default), and showing a message about how to change it afterwards.

I had to do some searching to find the answer.

**Comment by tbruckmaier** [comment]
On my machine, there are two video devices:

```
$ ls /dev/video*
/dev/video0  /dev/video1
```

My webcam is `video0` but lolcommits uses `video1` now per default. I have fixed it as suggested via `LOLCOMMITS_DEVICE="/dev/video0"` and it is working now. I would have assumed though that the *first* device is used (as it was doing before).

Apparently `Dir.glob('/dev/video*').first` from c639c06 does not do any sorting, so on my machine(?) it returns `video1`. I am no ruby dev, but have found this https://stackoverflow.com/questions/4814340/alphabetize-results-of-dir-glob/24039742 . Probably would make sense to add `sort`, so the results are at least always the same on all machines.

**Comment by rvangsgaard** [comment]
I have four video devices, but the first is the one I use. So in my case, a sort before selected the first would also work, as @tbruckmaier
