### ISSUE TITLE
No annotations on image

### ISSUE THREAD

**Issue by Holek** [mroth/lolcommits#88]
Hi, I'm using OSX, `lolcommits-0.4.1pre1` and `LOLCOMMITS_DEBUG=1`

The capture is done, but not annotated. Here's output:

<pre>
$ lolcommits --capture     
Outputting at DEBUG verbosity
Runner: Making sure user isn't rebasing
Plugin: Lolcommits::Tranzlate: Initializing
Plugin: Lolcommits::Tranzlate: Disabled, doing nothing for execution
*** Preserving this moment in history.
Capturer: initializing new instance #<Lolcommits::CaptureMac:0x007f9a3d0e9af0>
Capturer: making system call for /Users/holek/.rvm/gems/ruby-1.9.3-p125-perf@global/gems/lolcommits-0.4.1pre1/lib/lolcommits/../../vendor/ext/imagesnap/imagesnap -q "/Users/holek/.lolcommits/code/tmp_snapshot.jpg" -w 0 
Runner: resizing snapshot
Runner: copying resized image to /Users/holek/.lolcommits/code/b64f8b5961e.jpg
Plugin: Lolcommits::Loltext: Initializing
Plugin: Lolcommits::Loltext: I am enabled, about to run
Plugin: Lolcommits::Loltext: Annotating image via MiniMagick
Plugin: Lolcommits::Loltext: Writing changed file to /Users/holek/.lolcommits/code/b64f8b5961e.jpg
Plugin: Lolcommits::DotCom: Initializing
Plugin: Lolcommits::DotCom: Disabled, doing nothing for execution
Plugin: Lolcommits::StatsD: Initializing
Plugin: Lolcommits::StatsD: I am enabled, about to run
Plugin: Lolcommits::LolTwitter: Initializing
Plugin: Lolcommits::LolTwitter: Disabled, doing nothing for execution
Plugin: Lolcommits::Lolsrv: Initializing
Plugin: Lolcommits::Lolsrv: Disabled, doing nothing for execution
Plugin: Lolcommits::Uploldz: Initializing
Plugin: Lolcommits::Uploldz: Disabled, doing nothing for execution
Runner: running cleanup
</pre>

**Comment by Tak** [comment]
I had this issue briefly - it turned out that my imagemagick package was the no-xquartz one from http://cactuslab.com/imagemagick , which doesn't include the freetype delegates.
