### ISSUE TITLE
investigate moving plugins out of main gem

### ISSUE THREAD

**Issue by mroth** [mroth/lolcommits#99]
It would be neat to have plugins be their own gems that somehow extend the functionality of lolcommits.  

Goals for this:
- Reduce dependency chain for "normal" lolcommits installation (we do install more gems than I'd prefer right now)
- Mitigate the maintenance debt from plugin bloat.
- Enable people to add plugins more easily (more of a nice side effect than a primary goal in honesty)

Things this would be used for:
- Large functionality extension such as uploading to a web service (e.g. the twitter functionality) that require additional gems to function.

Things it wouldn't be used for:
- Normal feature additions to the core lolcommits program without extra dependencies, such as the recent animated gif patch (#95).

However, I have no idea how to proceed with such an endeavor, if anyone has documentation or sample code they could point me at I would appreciate it!

**Comment by mroth** [comment]
From memory, the most recent way we had been thinking about this was:

1. All plugins basically extend the Plugin class and are packaged as Gemfiles.  Lolcommits main will scan for anything installed globally under a specific namespace (e.g. `lolcommits-plugin-*`) and load/execute it.

2. We provide a default plugin template to make it easy for people to get started. Migrating most plugins to this format would simply involve copy pasting and specifying dependencies.

3. Use the model that Boxen uses for PRs:

  > "If you've got a Boxen module you'd like to be grouped under the Boxen org, (so it can easily be found by others), please file an issue on this repository with a link to your module. We'll review the code briefly, and if things look pretty all right, we'll fork it under the Boxen org and give you read+write access to our fork. You'll still be the maintainer, you'll still own the issues and PRs. It'll just be listed under the boxen org so folks can find it more easily."

  This way contributors can continue to own and update their plugins.
 
4. Even default plugins should be converted to gems with their own repos in a lolcommits org on GitHub. In this case, "default" just starts to mean "specified in the .gemspec" -- but we still get the benefits of versioning and better dependency management.

**Comment by mroth** [comment]
I'm still rather liking the solution discussed above.  My biggest worry about it however is it further ties us to the rubygems world, and _could_ potentially complicate moving to homebrew packaging or something like that in the future.

@matthutchinson, thoughts?

**Comment by matthutchinson** [comment]
@mroth, I think its ok to remain tied to the Ruby gems world for now.  At the moment, it is a shorter path of work to get the plugin code out of the core lolcommits gem first.  I think this will help define the core codebase for lolcommits and may lead to some further cleanup & refactoring.

Tackling a large architecture change now (e.g. moving away from Ruby gems), with the current weight of code and dependencies we have from plugins would be a bigger task.  I think the smallest step to take in the right direction is to move the plugin code out first.

I could hit the ground running some day this week to get a branch spiked, or I'd be up for pairing too, if the time difference isn't an issue :clock11: :smile:

**Comment by mroth** [comment]
@matthutchinson Yeah, I'm thinking we stick with ruby gems as distribution system too.

Ping me on IRC/gchat/email and we can figure out if we can coordinate timing to pair!

**Comment by matthutchinson** [comment]
I'm actually traveling a bit this week so I'm unsure when I'll be available.  I'm back in London next week tho, and will ping you on email to arrange a time.

**Comment by mroth** [comment]
As part of looking over the class and module structure noticed all plugins are currently part of `Lolcommits` module directly, e.g. `Lolcommits::LolTwitter` etc.  We should probably namespace them as part of a nested `Lolcommits::Plugin` module namespace.

**Comment by matthutchinson** [comment]
:+1: yep makes sense

**Comment by matthutchinson** [comment]
Worked on this at the weekend, should have a PR this week, its looking good so far !

**Comment by matthutchinson** [comment]
@mroth can you grant me admin privileges on this repo? https://github.com/lolcommits/lolcommits-plugin-sample

I've re-created this sample gem with the latest bundler version - and have it almost ready to go with the some new PluginManager code.  Id like to replace what you started their last year..

**Comment by mroth** [comment]
@matthutchinson try now.  I just "migrated" our old lolcommits teams to the new GitHub teams model and updated the permissions, I believe @lolcommits/core should now convey admin powers to all org repos.

**Comment by matthutchinson** [comment]
All good now - thanks! 👋

**Comment by matthutchinson** [comment]
Seems I can't create new repos... I'll need to do this for each of the plugins.

<img width="746" alt="screen shot 2017-01-08 at 21 49 10" src="https://cloud.githubusercontent.com/assets/2095/21753811/52a9d330-d5ec-11e6-9da2-15ef6635b940.png">

**Comment by mroth** [comment]
Huh, let me see if I can figure out what the missing permission is.  Core should have full admin.

**Comment by mroth** [comment]
Okay, weird, creating new repositories is totally separate from team permissions:
<img width="986" alt="screen shot 2017-01-08 at 4 53 13 pm" src="https://cloud.githubusercontent.com/assets/40650/21753839/01071944-d5c3-11e6-971e-29b551f61986.png">

This is now enabled.  But I guess it unfortunately means that for every new repository you create, we will have to manually add it to the @lolcommits/core team in permissions. Ah well!  LMK if you figure out a better workaround, but you should have full permissions for that now too.

**Comment by matthutchinson** [comment]
Thanks for fixing that, works now.  

So I've recreated https://github.com/lolcommits/lolcommits-plugin-sample repo now (and added core as admin).  I have a bunch of TODO's in there, tests to write and documentation to add.  

I will explain all this further in a PR soon (hopefully this week). 

Initially, for a first release, I'm planning to have the sample plugin done and well documented, and the core loltext plugin fully extracted.  From there it will be pretty trivial to move the others out.

**Comment by matthutchinson** [comment]
🎩  TADA - https://github.com/mroth/lolcommits/pull/332 - for review

**Comment by matthutchinson** [comment]
#332 is now merged - will close this guy when all plugins have been extracted ⛏

**Comment by matthutchinson** [comment]
#339 merged (default loltext plugin) remaining todo list;

- [ ] plugin-sample    
- [ ] loltext    
- [ ] dot_com    
- [ ] flowdock   
- [ ] hipchat    
- [ ] lolprotonet
- [ ] lolsrv     
- [ ] slack      
- [ ] term_output
- [ ] tranzlate  
- [ ] tumblr     
- [ ] twitter    
- [ ] uploldz    
- [ ] yammer

**Comment by matthutchinson** [comment]
It is done! Well all the plugins have been extracted to gems, I still have some follow up todo's I've been tracking in this [project](https://github.com/mroth/lolcommits/projects/1) and I'll release 0.9.8 soon - two gem plugins depend on that release.

**Comment by mroth** [comment]
Super exciting! I'm actually without a development machine for the next
month while traveling (trying out dat iPad life, we'll see if I go into
withdrawal or not), but really looking forward to trying this when I get
back. Great work.

On Sat, Dec 2, 2017 at 6:14 PM, Matthew Hutchinson <notifications@github.com

**Comment by matthutchinson** [comment]
I'm going to close this issue now, with the latest release `0.9.8` supporting gem plugins and all plugins now extracted 😄  - I've updated the README and [wiki](https://github.com/mroth/lolcommits/wiki/Configuring-Plugins) too.
